site_name: NOMI-Wiki
site_description: NOMI Wiki
site_author: NOMI
site_url: https://nomizy.github.io/
repo_name: NOMI-wiki
repo_url: https://github.com/NOMIzy/nomizy.github.io
copyright: Copyright &copy; 2024 - Future NOMI
remote_branch: master
theme:
  name: material
  language: en
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: https://github.com/NOMIzy/resource_repository/raw/master/nomi.png
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
- search
- minify:
    minify_html: true
nav:
- Introduction: 
  - introduction/intro.md
- 数据编码与存储:
  - data_encode_store/introduction.md
  - 字符编码格式:
    - data_encode_store/encode_char.md
  - 文件格式:
    - 文本:
      - data_encode_store/encode_file_txt.md
    - 图像:
      - data_encode_store/encode_file_picture.md
    - 视频:
      - data_encode_store/encode_file_video.md
    - 音频:
      - data_encode_store/encode_file_audio.md
    - 3D资产:
      - data_encode_store/encode_file_3d.md
  #- 常用存储:
- 数据获取:
  - data_access/introduction.md
  #- 从设备获取数据:
  #- 从数据库获取数据:
  #- 从网络API获取数据:
  #- 实体间通信:
- 数据处理:
  - data_process/introduction.md
  #- 编码格式处理:
  #- 文件格式处理:
  - 常用数据结构处理:
    - data_process/basic_algorithm/intro.md
    - 基本算法:
      - STL:
        - data_process/basic_algorithm/STL/STL.md
      - 字符串:
        - data_process/basic_algorithm/string/string.md

  #  - 数组:
  #  - 链表:
  #  - 树:
  #  - 堆:
  #  - 图:
  #- 较复杂问题:
  #  - CV:
  #  - NLP:
  #  - DL:
  #  - RL:
- 应用集成:
  - application/introduction.md
  - 通信:
    - application/LLMG/communication_between_upper_and_lower_machine.md
  #- 常见框架的适用场合:
  #- 各类型数据呈现:
  #- 界面跳转:
- 随笔:
  - think/行业选择.md
